# Generated by Django 3.1.4 on 2022-02-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name_plural': 'Mobile Banner',
            },
        ),
        migrations.CreateModel(
            name='MCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Maxsulot Savatchada'), ('2', 'Sotib olingan')], default=1, max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mobile Cart',
            },
        ),
        migrations.CreateModel(
            name='MobilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=200, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mobile Users',
            },
        ),
        migrations.CreateModel(
            name='Telegramid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='debtor',
            name='debt_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='debt_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MyOwnToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.mobiluser', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Mobile Token',
                'verbose_name_plural': 'Mobile Tokens',
            },
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='api.MCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser')),
            ],
            options={
                'verbose_name_plural': 'Mobile order',
            },
        ),
        migrations.AddField(
            model_name='mcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
    ]
