# Generated by Django 3.1.4 on 2022-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220202_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpayhistory',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
