# Generated by Django 3.1.4 on 2022-02-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deliverpayhistory_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_product', to='api.filial'),
        ),
    ]
