# Generated by Django 3.1.4 on 2022-02-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220221_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_pay', to='api.filial'),
        ),
    ]
