# Generated by Django 3.1.4 on 2022-02-22 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220222_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
