# Generated by Django 3.1.4 on 2022-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_debtor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='nasiya_foiz',
            field=models.FloatField(default=0),
        ),
    ]
