# Generated by Django 3.1.4 on 2022-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_filial_nasiya_foiz2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nasiya_foiz',
            field=models.FloatField(default=0),
        ),
    ]
