# Generated by Django 3.1.4 on 2022-03-14 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cashboxreceive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxreceive',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashboxreceive',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
