# Generated by Django 3.1.4 on 2022-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220314_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxreceive',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='waiting', max_length=255),
        ),
    ]
