# Generated by Django 3.1.4 on 2022-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220314_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxreceive',
            name='total_sum',
            field=models.FloatField(),
        ),
    ]
