# Generated by Django 3.1.4 on 2022-03-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220314_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiqim',
            old_name='qayerga',
            new_name='category',
        ),
        migrations.AddField(
            model_name='chiqim',
            name='to_where',
            field=models.CharField(default='lorem ipsum dolor', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChiqimSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chiqimturi')),
            ],
        ),
    ]
