# Generated by Django 3.1.4 on 2022-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220318_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqimsubcategory',
            name='to_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chiqimsubcategory',
            name='to_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
