# Generated by Django 3.1.4 on 2022-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220318_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='dollar_rate',
            field=models.PositiveIntegerField(default=11000),
            preserve_default=False,
        ),
    ]
