# Generated by Django 3.1.4 on 2022-03-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_shop_dollar_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Filial chiqim turi',
                'verbose_name_plural': 'Filial chiqim turlari',
            },
        ),
        migrations.AlterField(
            model_name='cashboxreceive',
            name='currency',
            field=models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar')], default='dollar', max_length=20),
        ),
        migrations.CreateModel(
            name='FilialExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('total_sum', models.FloatField()),
                ('currency', models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar')], default='dollar', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filialexpensecategory')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
        ),
    ]
