# Generated by Django 3.1.4 on 2022-03-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220326_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filialexpense',
            options={'verbose_name': 'Filial chiqim', 'verbose_name_plural': 'Filial chiqimlar'},
        ),
    ]
