# Generated by Django 3.1.4 on 2022-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220327_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='qancha_dol',
            field=models.FloatField(default=0),
        ),
    ]
