# Generated by Django 3.1.4 on 2022-04-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220407_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='last_filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
