# Generated by Django 3.1.4 on 2022-04-08 06:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0026_debtor_last_filial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recieve',
            new_name='Receive',
        ),
        migrations.RenameModel(
            old_name='RecieveItem',
            new_name='ReceiveItem',
        ),
        migrations.AlterModelOptions(
            name='receive',
            options={'verbose_name_plural': '4) Receive'},
        ),
        migrations.AlterModelOptions(
            name='receiveitem',
            options={'verbose_name_plural': '4.1) ReceiveItem'},
        ),
        migrations.RenameField(
            model_name='receiveitem',
            old_name='recieve',
            new_name='receive',
        ),
    ]
