# Generated by Django 3.1.4 on 2022-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220408_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='products',
            field=models.ManyToManyField(through='api.ReceiveItem', to='api.ProductFilial'),
        ),
    ]
