# Generated by Django 3.1.4 on 2022-04-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_receive_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='products',
            field=models.ManyToManyField(blank=True, through='api.ReceiveItem', to='api.ProductFilial'),
        ),
        migrations.AlterField(
            model_name='receiveitem',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.receive'),
        ),
    ]
