# Generated by Django 3.1.4 on 2022-04-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220409_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakturaitem',
            name='barcode',
        ),
    ]
