# Generated by Django 3.1.4 on 2022-04-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_productfilial_ombor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturaitem',
            name='price_diff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiveitem',
            name='price_diff',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fakturaitem',
            name='faktura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.faktura'),
        ),
        migrations.AlterField(
            model_name='fakturaitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktura_items', to='api.productfilial'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
