# Generated by Django 3.1.4 on 2022-04-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220411_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveitem',
            name='price_diff',
        ),
    ]
