# Generated by Django 3.1.4 on 2022-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220516_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
