# Generated by Django 3.1.4 on 2022-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220516_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
