# Generated by Django 3.1.4 on 2022-05-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220518_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
