# Generated by Django 3.1.4 on 2022-05-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220518_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
