# Generated by Django 3.1.4 on 2022-05-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220518_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='HisobdanChiqarishOmbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparer', models.CharField(default='', max_length=255)),
                ('som', models.FloatField(default=0)),
                ('sotish_som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('sotish_dollar', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=123)),
                ('quantity', models.FloatField(default=0)),
                ('expired_date', models.DateField(blank=True, default='2022-05-22', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=125)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QaytganProductOmbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparer', models.CharField(default='', max_length=255)),
                ('som', models.FloatField(default=0)),
                ('sotish_som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('sotish_dollar', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=123)),
                ('quantity', models.FloatField(default=0)),
                ('expired_date', models.DateField(blank=True, default='2022-05-22', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fakturaitem',
            name='expired_date',
            field=models.DateField(blank=True, default='2022-05-22', null=True),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='expired_date',
            field=models.DateField(blank=True, default='2022-05-22', null=True),
        ),
        migrations.AddField(
            model_name='receiveitem',
            name='expired_date',
            field=models.DateField(blank=True, default='2022-05-22', null=True),
        ),
        migrations.CreateModel(
            name='YuqFakturaSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('item', models.ManyToManyField(to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Yetkazilgantavar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparer', models.CharField(default='', max_length=255)),
                ('som', models.FloatField(default=0)),
                ('sotish_som', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('sotish_dollar', models.FloatField(default=0)),
                ('kurs', models.FloatField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('measurement', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('metr', 'metr')], default='dona', max_length=4)),
                ('min_count', models.FloatField(default=0)),
                ('ombor', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('expired_date', models.DateField(blank=True, default='2022-05-22', null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yetkazilgan_product', to='api.filial')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Hisobdan_cgiqarish_filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('t_price', models.FloatField()),
                ('price', models.FloatField()),
                ('valuta', models.CharField(choices=[('uz', 'UZ'), ('$', '$')], default='uz', max_length=150)),
                ('quantity', models.FloatField()),
                ('barcode', models.CharField(max_length=125)),
                ('guruh', models.CharField(max_length=125)),
                ('measurement', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('metr', 'metr')], default='dona', max_length=125)),
                ('preparer', models.CharField(max_length=125)),
                ('expired_date', models.DateField(blank=True, default='2022-05-22', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
        ),
    ]
