# Generated by Django 3.1.4 on 2022-05-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220524_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepriceitem',
            name='changeprice',
        ),
        migrations.RemoveField(
            model_name='changepriceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='changepriceitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cashboxreceive',
            name='total_dollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changepriceitem',
            name='barcode',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='changepriceitem',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.AlterField(
            model_name='cashboxreceive',
            name='currency',
            field=models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar'), ('carta', 'carta'), ('utkazma', 'utkazma')], default="so'm", max_length=20),
        ),
        migrations.AlterField(
            model_name='filialexpense',
            name='currency',
            field=models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar'), ('carta', 'carta'), ('utkazma', 'utkazma')], default="so'm", max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='dollar_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='naqd_dollar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='naqd_som',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='nasiya_dollar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='nasiya_som',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='plastik',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='skidka_dollar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='skidka_som',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='transfer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
