# Generated by Django 3.1.4 on 2022-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220525_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrival_price_som',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='selling_price_som',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qaytganproductombor',
            name='farqi_dollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaytganproductombor',
            name='farqi_som',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fakturaitem',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdan_cgiqarish_filial',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='group',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productfilial',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qaytganproductombor',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiveitem',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yetkazilgantavar',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
